### ISSUE TITLE
uploads support amazon s3

### ISSUE THREAD

**Issue by gutenye** [citrus/spree_essentials#3]
It'll be very nice if we can upload files into amazon s3, especial for apps deployed to heroku.

**Comment by citrus** [comment]
I chose to leave this out of the extension since it's easy enough to add to your project, and some folks may prefer a different CDN other than s3. 

To use s3 for your uploads, add a file in your project called `app/models/upload_decorator.rb` and make it look something like this:

``` ruby
Spree::Upload.attachment_definitions[:attachment].merge!(
  :storage        => 's3',
  :s3_credentials => Rails.root.join('config', 's3.yml'),
  :path           => "/uploads/:id/:style/:basename.:extension"
)
```

Now configure s3 in `config/s3.yml`

``` yml
defaults: &defaults
  access_key_id: YOUR_KEY
  secret_access_key: YOUR_SECRET
  s3_protocol: http

development:
  <<: *defaults
  bucket: yoursite.dev

test:
  <<: *defaults
  bucket: yoursite.test

production:
  <<: *defaults
  bucket: yoursite.com
```

If you're using the CMS or blog extension as well, configure them the same way:

``` ruby
[ Spree::Content, Spree::PageImage, Spree::PostImage, Spree::Upload ].each do |cls| 
  cls.attachment_definitions[:attachment].merge!(
    :storage        => 's3',
    :s3_credentials => Rails.root.join('config', 's3.yml'),
    :path           => "/uploads/:id/:style/:basename.:extension"
  )
end
```

Let me know if you have any questions!

-Spencer
